### ISSUE TITLE
Editorial suggestion: Explain what stays the same in the README

### ISSUE THREAD

**Issue by littledan** [syg/proposal-rm-builtin-subclassing#2]
For example:
- We still have all the RegExp symbols like `Symbol.match`, `Symbol.replace`, etc; those are fine
- You can still subclass Array, and instantiating that subclass will use all the `new.target` logic that we got in ES6

**Comment by syg** [comment]
Does the new taxonomy section and the explanation that this proposal seeks to remove Types II, III, and IV, but not I (`new.target`) make this clear?

**Comment by littledan** [comment]
This section helps a lot for `new.target`. I still think it would be useful to explain that the delegation of String.prototype.match to Symbol.match stays in place (maybe in the String or RegExp sections).

**Comment by domenic** [comment]
> the delegation of String.prototype.match to Symbol.match stays in place (maybe in the String or RegExp sections).

Does it? That'd be sad :(.

**Comment by syg** [comment]
> Does it? That'd be sad :(.

@@match is more like a protocol IMO and not about subclassing per se. Removal of them is a different web compat question and language design question than trying to remove subclassing. For those reasons this proposal doesn't seek to remove Symbol.match.

The compat question is: "Do people use custom RegExp-like currently for Strings?"

The language question is: "Should we support custom built-in-likes for arguments of built-in methods?" This question has more implications beyond Strings' use of RegExps. I know @bakkot would like proposals of methods like Set#difference or Set#union to be able to take Set-likes.

All that said I'm not proposing to remove them here as a tactical thing. There's enough compat risk here already.

**Comment by codehag** [comment]
> @@match is more like a protocol IMO and not about subclassing per se. Removal of them is a different web compat question and language design question than trying to remove subclassing. For those reasons this proposal doesn't seek to remove Symbol.match.

We are fine with this. The main complexity we have around RegExp is checking these properties are not defined on String.prototype so that we can optimize the non-regexp case. 

> All that said I'm not proposing to remove them here as a tactical thing. There's enough compat risk here already.

I agree with this. The proposal, as is, is already pretty daunting. If this is successful we can look at other interventions in the future.

cc @jandem as he knows more about this area.
