### ISSUE TITLE
Ambiguity about what this does for static methods in subclasses

### ISSUE THREAD

**Issue by littledan** [syg/proposal-rm-builtin-subclassing#3]
This text from the Promise constructor methods section is confusing:

> This means any subclass calling these methods on the subclass constructor will always get Promise instances back, or throw if not called with Promise as the receiver.
>
> ```js
> class MyPromise extends Promise { /* ... * / }
> let mp = MyPromise.resolve(() => {});
> // Result is an Promise, not a MyPromise.
> ```

Are you proposing that this code would throw or not? I think that, based on everything else in the document, we shouldn't throw, and just ignore the receiver. (c.f., #1 )

**Comment by syg** [comment]
Oops, this should be fixed. I have fixed the explainer to say that it ignores the receiver.
