### ISSUE TITLE
Leave IsRegExp out of this?

### ISSUE THREAD

**Issue by littledan** [syg/proposal-rm-builtin-subclassing#4]
I think that logic is a bit silly, but it's not hurting anyone. Ultimately it's kind of in the same camp as things like Symbol.match, Symbol.replace, that are superficial and easy to implement.

**Comment by syg** [comment]
Out of String methods, or out of both RegExp and String methods?

**Comment by littledan** [comment]
Oh right, we would just maintain IsRegExp in string methods, not RegExp-internal ones.

**Comment by syg** [comment]
Resolved by #8.
